export default {
    'address': [ 'id', 'address_line', 'zip_code', 'city_id' ],
    'city': [ 'id', 'city', 'department_id' ],
    'department': [ 'id', 'department' ],
    'person': [ 'id', 'first_name', 'last_name', 'doc_type', 'doc_number', 'email', 'address_id' ],
    'user': [ 'id', 'password', 'role_id', 'university_actor_id', 'university_actor_person_id' ],
    'university_actor': [ 'id', 'username', 'email', 'person_id', 'campus_id' ],
    'role': [ 'id', 'role' ],
    'campus': [ 'id', 'campus', 'address_id' ],
    'card': [ 'id', 'owner', 'card_number', 'card_type_id', 'card_category_id', 'person_id' ],
    'card_type': [ 'id', 'type' ],
    'card_category': [ 'id', 'category' ],
    'operation_status': [ 'id', 'status' ],
    'payment_concept': [ 'id', 'concept', 'description', 'amount' ],
    'invoice': [ 'id', 'date', 'due_date', 'description', 'invoice_number', 'payment_id' ],
    'payment': [ 'id', 'credit_card_authorization_code', 'amount', 'balance', 'date', 'effective_date', 'gateway_date', 'reference_number', 'num_installments', 'fulfilled', 'operation_status_id', 'payment_concept_id', 'person_id', 'campus_id', 'card_id' ],
    'balance_query': [ 'id', 'date', 'effective_date', 'operation_status_id', 'person_id' ],
    'card_balance_query': [ 'id', 'balance', 'gateway_date', 'operation_status_id', 'balance_query_id', 'card_id' ],
}
